name: CI → Heroku CD

on:
  push:
    branches: [ main ]   # or change to 'master' if that's your default branch

jobs:
  build-and-test:
    name: 🔨 Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend deps
        run: npm ci

      - name: Install frontend deps
        run: npm ci --prefix frontend

      - name: Build frontend (ignore CRA warnings)
        run: |
          CI=false npm run build --prefix frontend

      - name: Run tests
        run: npm test

  deploy:
    name: 🚀 Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-test.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Heroku via Git
        run: |
          # Add Heroku remote with API key embedded for HTTPS auth
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          # Push your main branch
          git push heroku HEAD:main --force
