name: CI → Heroku CD

on:
  push:
    branches: [ main ]   # or change to 'master' if your default branch is named master

jobs:
  build-and-test:
    name: 🔨 Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend & backend
        env:
          CI: false
        run: npm run build

      - name: Run tests
        run: npm test

  deploy:
    name: 🚀 Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ needs.build-and-test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "$HEROKU_API_KEY" | heroku auth:token

      - name: Push to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku HEAD:main --force
