# .github/workflows/ci-cd-heroku.yml
name: CI → Heroku CD

on:
  push:
    branches: [ main ]  # or replace with 'master' if that’s your branch

jobs:
  build-and-test:
    name: 🔨 Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend deps
        run: npm ci

      - name: Install frontend deps
        run: npm ci --prefix frontend

      - name: Build frontend (ignore CRA warnings)
        run: |
          CI=false npm run build --prefix frontend

      - name: Run tests
        run: npm test

  deploy:
    name: 🚀 Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize Git
        run: |
          git init
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3
        with:
          heroku_api_key:   ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name:  ${{ secrets.HEROKU_APP_NAME }}
          heroku_email:     ${{ secrets.HEROKU_EMAIL }}
