name: CI → Heroku CD

on:
  push:
    branches: [ main ]   # change to master if needed

jobs:
  build-and-test:
    name: 🔨 Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend deps
        run: npm ci

      - name: Install frontend deps
        run: npm ci --prefix frontend

      - name: Build frontend & backend (ignore CRA warnings)
        run: |
          # build backend if you had any backend build step (otherwise skip)
          # now build React app with CI=false so warnings won't fail
          CI=false npm run build --prefix frontend

      - name: Run tests
        run: npm test

  deploy:
    name: 🚀 Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-test.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "$HEROKU_API_KEY" | heroku auth:token

      - name: Push to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          git push heroku HEAD:main --force
