name: CI → Heroku CD

on:
  push:
    branches: [ main ]   # adjust if your default is 'master'

jobs:
  build-and-test:
    name: 🔨 Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install backend deps
        run: npm ci

      - name: Install frontend deps
        run: npm ci --prefix frontend

      - name: Build frontend (ignore CRA warnings)
        run: |
          CI=false npm run build --prefix frontend

      - name: Run tests
        run: npm test

  deploy:
    name: 🚀 Deploy to Heroku
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ needs.build-and-test.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Heroku remote with API key
        run: |
          # Remove any existing heroku remote
          git remote remove heroku || true
          # Embed API key into the remote URL for HTTPS auth:
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

      - name: Push to Heroku
        run: |
          git push heroku HEAD:main --force
